//wavファイルリスト（ファイル名＋改行だけが並ぶファイル、dir *.wav /b > filelist.txtで取れます）から、
//それぞれlame ???.wav ???.mp3と変換したテキストファイルを作る秀丸マクロ。
//出来たファイルをコピーしてプロンプト画面にペーストすれば一括変換可能
//他にもいろんなツールに応用可能です。

gofiletop;
while (1) {
insert "lame ";
$str=gettext (x,y,x+9,y);
golineend2;
insert " ";
while (1) {
  if (rightstr($str,1)==".") {
    $str=leftstr($str,strlen($str)-1);
    break;
  }
  $str=leftstr($str,strlen($str)-1);
}
insert $str;
insert ".mp3";
#n=lineno;
right;
if (#n==lineno) break;
}
